name: Create Release

on:
  workflow_run:
    workflows:
      - "Run Tests" # Only run this workflow if Test completes
    branches:
      - master
      - next
      - beta
      - "*.x" # maintenance releases branches
      - renovate/**
    types:
      - completed

  workflow_dispatch:

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          cache: npm

      - name: Install dependencies
        run: npm ci
        env:
          HUSKY: 0

      - name: Run release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
