name: Run Tests

on:
  push:
    branches:
      - master
      - next
      - beta
      - "*.x" # maintenance releases branches
      - renovate/**

  pull_request:
    types:
      - opened
      - synchronize

  workflow_dispatch:

jobs:
  test_matrix:
    strategy:
      matrix:
        node-version:
          - 12
          - 14
          - 16
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Test on Node.js ${{ matrix.node-version }} and ${{ matrix.os }}
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run test ${{ matrix.os }}
        if: ${{ matrix.os != 'windows-latest' }}
        run: npm run test:ci

      - name: Run test ${{ matrix.os }}
        if: ${{ matrix.os == 'windows-latest' }}
        run: npm run test:ci:win

  # separate job to set as required in branch protection,
  # as the build names above change each time Node versions change
  test:
    runs-on: ubuntu-latest
    needs: test_matrix
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint
